version: '3'

services:
    gtfs-auto-import:
        image: gtfs-auto-import:latest
        container_name: gtfs-auto-import-${OPERATOR}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4003:4003
        restart: on-failure
        networks:
            - gtfs-network
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gtfs-postgres:5432/gtfs_${OPERATOR}
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=3gXdM!!X9aG49yBN3
            - IMPORT_READY_URL=http://gtfs-app:${PORT_STATIC}/api
            - GTFS_SOURCE_URL=${GTFS_SOURCE_URL}
            - GTFS_IMPORT_URL=http://gtfs-app:${PORT_STATIC}/api/gtfs/import
            - GTFS_DOWNLOAD_DIR=${GTFS_DOWNLOAD_DIR}
            - CHB_SOURCE_URL=${CHB_SOURCE_URL}
            - CHB_IMPORT_URL=http://gtfs-app:${PORT_STATIC}/api/chb/import
            - CHB_DOWNLOAD_DIR=${CHB_DOWNLOAD_DIR}
            - PSA_SOURCE_URL=${PSA_SOURCE_URL}
            - PSA_IMPORT_URL=http://gtfs-app:${PORT_STATIC}/api/psa/import
            - PSA_DOWNLOAD_DIR=${PSA_DOWNLOAD_DIR}
            - CRON_EXPRESSION_AUTO_IMPORT_SCHEDULE=${CRON_EXPRESSION_AUTO_IMPORT_SCHEDULE}
            - IMPORT_MODE=${IMPORT_MODE}

networks:
    gtfs-network:
        external: true
        name: gtfs-network